import Head from "next/head";
import React, { useRef } from "react";
import styled from "styled-components";
import Accordion from "../components/Accordion";
import { motion } from "framer-motion";

const Section = styled.section`
  height: 100%;
  width: 100%;
  background: linear-gradient(rgba(0, 0, 0, 1), transparent);
  position: relative;
  background-color: firebrick;

  display: flex;
  justify-content: center;
  align-items: flex-start;
  flex-direction: column;
`;

const Title = styled.h1`
  font-size: 3em;
  font-family: "audiowide";
  text-transform: uppercase;
  color: floralwhite;
  transition: all 0.2s ease-in-out;

  padding-top: 3rem;
  padding-left: 2rem;
  width: fit-content;

  @media (max-width: 64em) {
    font-size: 2.7em;
  }
  @media (max-width: 48em) {
    font-size: 2.4em;
  }
`;
const Container = styled.div`
  width: 90%;
  padding-left: 3rem;
  padding-bottom: 3rem;
  display: flex;
  align-content: flex-start;

  @media (max-width: 64em) {
  }

  @media (max-width: 48em) {
    flex-direction: column;

    & > *:last-child {
      & > *:first-child {
      }
    }
  }
`;

const Box = styled.div`
  width: 80%;

  @media (max-width: 64em) {
    width: 80%;
  }
`;

const FAQ = () => {
  const ref = useRef(null);

  return (
    <>
      <Head>
        <title>Ō-Inari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ y: 25, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{
          delay: 0.45,
          duration: 0.75,
        }}
      >
        <Section ref={ref}>
          <Title>FAQ</Title>
          <Container>
            <Box>
              <Accordion title="Who is Ō-Inari and what are Fox Familiars?">
                Patron of prosperity, harvests, tea, and smithing, Ō-Inari has
                Fox Familiars assist with ventures across various realms and
                multiverses. These Sly Fox Familiars are now your companions from the
                Metaverse.
              </Accordion>
              <Accordion title="What can I do with my Sly Fox?">
                Sly Fox owners are given unlimited, worldwide license to
                use, copy and display their purchased Fox for personal use.
                Carefully read 'TERMS AND CONDITIONS' below to understand the
                full ownership of your NFT.
              </Accordion>
              <Accordion title="Which network will the NFTs be on?">
                The best NFT Familiars to date are being hosted on the Ethereum
                network.
              </Accordion>
              <Accordion title="Where can I find the NFT after I mint?">
                The NFT(s) will be in your wallet and viewable on Opeansea. They
                will be revealed after 3 days or when the collection is sold
                out, which ever comes first. They will live on decentralized
                storage forever.
              </Accordion>
              <Accordion title="Who are the Kami mentioned in the Roadmap?">
                The Kami were the companions of the Sly Foxes prior to the
                Humans. Once the foxes are all adopted the Kami are said to
                make their appearance and join you as well.
              </Accordion>
              <Accordion title="What is in the future of Ō-Inari?">
                As stated in the roadmap, the Ultimate Goal is Divine Expansion.
                We will not make you any empty promises. We will seek to grow
                alliances with the outlook of bringing prosperity and valued
                ownership to the members (NFT Holders) of Ō-Inari.
              </Accordion>
            </Box>
          </Container>
        </Section>
      </motion.div>
    </>
  );
};

export default FAQ;
